### ISSUE TITLE
org.apache.hadoop.hive.metastore.SerDeStorageSchemaReader class not found

### ISSUE THREAD

**Issue by vishal98** [timveil/docker-hadoop-hive-metastore-standalone#1]
Hi,
We are trying to run presto using the standone metastore (using your docker image) and read avro format data .
We can do all crud operations on external table on s3  csv format  objects.
When we are trying same flow for avro format.,we can create table but reading or describe table is failing with following  error.

MetaException(message:org.apache.hadoop.hive.metastore.SerDeStorageSchemaReader class not found)
        at org.apache.hadoop.hive.metastore.utils.JavaUtils.getClass(JavaUtils.java:54)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.getStorageSchemaReader(HiveMetaStore.java:5201)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.get_fields_with_environment_context(HiveMetaStore.java:5174)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.get_fields(HiveMetaStore.java:5146)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

Docker Image Verison :timveil/docker-hadoop-hive-metastore-standalone:3.1.x

**Comment by vishal98** [comment]
using hive full image fixed it
